#ifndef PARCO_DEFS
#define PARCO_DEFS

#include <cstdint>

//Type alias, use this to change
//type used in the program
using MatType = float;

using Matrix = float*;

//Max value generated by the rand()
static constexpr MatType VALUE_MAX = 9.0f;

static constexpr uint32_t CACHE_LINE_SIZE = 64;
static constexpr uint32_t RECOMMENDED_BLOCK_SZ = CACHE_LINE_SIZE / sizeof(MatType);

#endif // !PARCO_DEFS
